language: node_js
node_js:
  - "node"
branches:
  only:
    - gh-pages
    - /.*/
before-install:
  - pip install --user pycodestyle
  - $(which npm) install -g jslint
before-script:
  - pycodestyle --max-line-length=100 .
  - npm run lint
script:
  - npm test
