const blueValleyHeadlines = [
  // Finance
  { headline: "khindy <i>zharifany</i>", isPositive: true },
  { headline: "<strong>forssellfritz</strong>", isPositive: false },
  { headline: "based on reality", isPositive: true },
  { headline: "<b>xlmdlx</b>", isPositive: true },
  { headline: "pacitan", isPositive: true },
  { headline: "kota yogyakarta", isPositive: false },
  { headline: "karimun", isPositive: true },
  { headline: "compton", isPositive: false },
  { headline: "thv", isPositive: false },
  { headline: "<s>peaceminusone</s>", isPositive: false },
  { headline: "bright character", isPositive: true },
  { headline: "california", isPositive: false },
  { headline: "vngnc", isPositive: false },
  { headline: "izzy", isPositive: false },
  { headline: "sacramento", isPositive: false },
  { headline: "marshall mathers", isPositive: false },
  { headline: "morii aimi", isPositive: true },
  { headline: "baskara putra", isPositive: true },
  { headline: "<strong>d.o</strong>", isPositive: false },
  { headline: "aftermath", isPositive: false },
  { headline: "synchronize", isPositive: false },
  { headline: "masuk-e", isPositive: true },
  { headline: "march 4th", isPositive: false },
  { headline: "14th season", isPositive: true },
  { headline: "pesawat kertas 365 hari", isPositive: false },
  { headline: "misuh, monolog, mokok", isPositive: true },
  { headline: "searchlight", isPositive: false },
  { headline: "john & david", isPositive: false },
  { headline: "sept 12, 2023", isPositive: true },
  { headline: "opening", isPositive: true },
  { headline: "log test", isPositive: true },
  { headline: "wrote", isPositive: true },
  { headline: "test", isPositive: true },
  { headline: "messed up", isPositive: true },
  { headline: "social media", isPositive: true },
  { headline: "writing skills", isPositive: true },
  { headline: "grammar", isPositive: true },
  { headline: "indo english", isPositive: true },
  { headline: "gatekeeper", isPositive: true },
  { headline: "setup", isPositive: true },
  { headline: "msi laptop", isPositive: true },
  { headline: "1050 gpu", isPositive: true },
  { headline: "m2 macbook air", isPositive: true },
  { headline: "iphone xs", isPositive: true },
  { headline: "moondrop starfield", isPositive: true },
  { headline: "logiteh g90", isPositive: true },
  { headline: "xbox wireless controller", isPositive: true },
  { headline: "egpu", isPositive: true },
  { headline: "windows setup", isPositive: true },
  { headline: "site hosted", isPositive: true },
  { headline: "netlify", isPositive: true },
  { headline: "autodeploy", isPositive: true },
  { headline: "github", isPositive: true },
  { headline: "free", isPositive: true },
  { headline: "inspired", isPositive: true },
  { headline: "from software game", isPositive: true },
  { headline: "story-telling", isPositive: true },
  { headline: "clue", isPositive: true },
  { headline: "item description", isPositive: true },
  { headline: "dialogue", isPositive: true },
  { headline: "vngnc/izzy", isPositive: false },
  { headline: "gitu dulu", isPositive: true },
  { headline: "semoga bermanfaat", isPositive: true },
  { headline: "kontak", isPositive: true },
  { headline: "email", isPositive: true },
  { headline: "icloud custom mail", isPositive: true },
  { headline: "sept 13, 2023", isPositive: true },
  { headline: "4 am", isPositive: true },
  { headline: "streaming", isPositive: true },
  { headline: "apple event", isPositive: true },
  { headline: "ios 17", isPositive: false },
  { headline: "macos 14", isPositive: false },
  { headline: "release date", isPositive: false },
  { headline: "iphone se", isPositive: false },
  { headline: "news", isPositive: true },
  { headline: "playlist", isPositive: true },
  { headline: "sept 25, 2023", isPositive: true },
  { headline: "change", isPositive: false },
  { headline: "page", isPositive: false },
  { headline: "direct html writing", isPositive: false },
  { headline: "message", isPositive: false },
  { headline: "reading", isPositive: false },
  { headline: "txt", isPositive: false },
  { headline: "sleep", isPositive: false },
];
