const blueValleyHeadlines = [
    // Finance
    { headline: "khindy <i>zharifany</i>", isPositive: true },
    { headline: "<strong>forssellfritz</strong>", isPositive: false },
    { headline: "based on reality", isPositive: true },
    { headline: "<b>xlmdlx</b>", isPositive: true },
    { headline: "pacitan", isPositive: true },
    { headline: "kota yogyakarta", isPositive: false },
    { headline: "karimun", isPositive: true },
    { headline: "compton", isPositive: false },
    { headline: "thv", isPositive: false },
    { headline: "<s>peaceminusone</s>", isPositive: false },
    { headline: "a ▀▀▀▀▀▀▀▀", isPositive: false },
    { headline: "bright character", isPositive: true },
    { headline: "california", isPositive: false },
    { headline: "sacramento", isPositive: false },
    { headline: "marshall mathers", isPositive: false },
    { headline: "morii aimi", isPositive: true },
    { headline: "baskara putra", isPositive: true },
    { headline: "<strong>d.o</strong>", isPositive: false },
    { headline: "aftermath", isPositive: false },
    { headline: "synchronize", isPositive: false },
    { headline: "masuk-e", isPositive: true },
    { headline: "march 4th", isPositive: false },
    { headline: "14th season", isPositive: true },
    { headline: "pesawat kertas 365 hari", isPositive: false },
    { headline: "misuh, monolog, mokok", isPositive: true },
    { headline: "searchlight", isPositive: false },
    { headline: "", isPositive: false },
    { headline: "john & david", isPositive: false },
    
    
];